backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow # allow direct push to github repository from CMS
media_folder: "src/images"
public_folder: "images"
collections:
  - name: "posts"
    label: "Posts"
    folder: "src/contents/posts"
    slug: "{{slug}}"
    preview_path: "posts/{{slug}}"
    create true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "SEO Meta Title", name: "metaTitle", widget: "string", required: false}
      - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
      - {label: "Publiash Date", name: "date", widget: "datetime"}
      - {label: "Cover Image", name: "coverImage", widget: "image", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "markdown", required: false}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
