backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  squash_merges: true # squash all commits into a single commit
publish_mode: editorial_workflow # allow direct push to github repository from CMS
site_url: "https://www.shisguang.com"
media_folder: "src/assets/images"
public_folder: "assets/images"
collections:
  - name: "posts"
    label: "Posts"
    folder: "src/contents/posts"
    slug: "{{year}}-{{month}}-{{day}}-{{fields.slug}}"
    preview_path: "posts/{{fields.slug}}"
    create: true
    fields:
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publiash Date", name: "date", widget: "datetime"}
      - {label: "Cover Image", name: "coverImage", widget: "image", required: false}
      - {label: "Disable Math", name: "disableKatex", widget: "boolean", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Table of Contents", name: "TOC", widget: "boolean", required: false}
      - label: "Script"
        name: "script"
        widget: "object"
        collapsed: true
        required: false
        fields:
          - {label: "link", name: "link", widget: "text", required: false}
          - {label: "inline", name: "inline", widget: "text", required: false}
